### ISSUE TITLE
Serialization function improvement

### ISSUE THREAD

**Issue by ellis-matthew4** [ellis-matthew4/XDL#8]
This thread is to come up with a better serialization function. The main problem with the current one is that it serializes the whole stack.
One possible workaround is to save just the current line, current script, and current label, then call the label upon load and quickly iterate through each line until a match is found. However, this does not work well in Godot because Dictionaries aren't meant to be directly compared.

**Comment by asheraryam** [comment]
Why not use the id/key of the line? Then it can be called directly instead of searching for it.

**Comment by ellis-matthew4** [comment]
@asheraryam This could also work, but if the dialogue file is changed, then the key could be wrong. Another problem is any lower layers of the stack need to be serialized as well. Just thinking to myself here: maybe create a state model of the stack that updates upon call() and return?

**Comment by asheraryam** [comment]
If the dialogue file changes, then I don't think any of these approaches would fix it.

* Saving the line and then changing the line contents in file means you won't find the line anymore.
* Saving the stack and then changing the dialogue means the stack is no longer valid and what you saved is actually an older version of the game.

That's why just take the simplest approach and save the key/id of the line, and if needed later for backwards compatibility, read the version number of the save file and convert it.

A lot of things can go wrong with saving the stack. What if the function behaviors change? What if you add a DLC update that adds new content, then trying to go back through the stack and reloading the sae file might lead the players to be somewhere else!

In roguelikes they usually only save the `seed` for the world and they use it to procedural generate the world instead of saving everything, but this breaks between every few versions when new content is added to the world.

**Comment by ellis-matthew4** [comment]
This is definitely an interesting idea, I'll have to keep it in mind. I will have to save the stack in some form or other, however. Otherwise, the game wouldn't be able to remember the context of the current scene, so when the current scene ends, the game won't have anywhere to go.
Example:
label1 is 15 lines long, label2 is 15 lines long
label1 calls label2 on label1-line10, saving label1-lines[11:15] to the stack and pushing label2
assume we save the game on lable2-line14
If the stack isn't saved, the game loads a stack containing only label2-lines[14:15]
One solution would be to have a list/dictionary model of the stack, formatted as
``
[ 0: { "labelName" : lineNumber },
  1: { "labelName" : lineNumber, ... ]
``

**Comment by ellis-matthew4** [comment]
Update to the problem: The solution to stack serialization I posted a few hours ago does not account for anonymous labels created by menus. If the player tried to save in a branch created by a menu, the save would be invalid. This could be resolved by removing anonymity by changing menu syntax to something like:
``
menu:
    option "Menu option here": <call | jump> <labelName>
``
Rather than what we have now:
``
menu:
    option "Menu option here":
        blah "blah blah"
        return
``

**Comment by ellis-matthew4** [comment]
Final solution, will be included in the next update: I am removing anonymous labels and the new option syntax mentioned before will be adopted.
